---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: eventhub-alerts
  namespace: eventhub
spec:
  encryptedData:
    discord-webhook-url: AgCX/Ad41Ox3Lx2DGd06geNefo4tiSMSAVeeY3ootbAcr7LVmTOVu3Tn4a8kxAPLjcrXbqDnGyQQApE18vrg/Ex/iP7BNWyTRPyHgNMniR3lBmnW9/YMimMmkiaTAup/f1fbY1MoRjXAMp58MqGasPuJor4WFarYBbgp24l0T2zKrAn+xi9/x5sD4+44W1GJr6gkHtQFkVyts+kMg3uc9LqbW8QMgAcBw/z/wnZz+KKpWN8aKx/GCXSu75lA1QUHQHuNIjHyiBCPsu3eVS/P1y+h7DW1XsLMVT9LguoGSaVQ5zqSzyioX9fcbESFhPeGYErBLazDGpSedAQpiu+qB+9XI8Sk1lCTgrzwTtWdxq1YFHRS7kWu+g+LriulsbbqplKYbSDtvZnDA6Gatuvlijkyd0uFWFMqAsmKSBz5rt/nBlGaZtnmpJ5/oa38iG2rDKGixDrBnXToMp1XHBAulCsnUgJm2tBKpLCydjcI0PmGOuDI8N0efImxlr40CtPUkeDQE+8DgoiNHXaPDY+8KaD4CZKno2UhkeHsstckKMCzOI0NnOxyoQKzR0DQoU98r7sFPmPE+2jpH7yBqWpdWn4JhbJPiUNZIWfQTxVrbzGu6ENDTyJe7tZ8BzZ4TfIomqqoxfSWmBIVaCIj2pR9b6bwqPasvthnw53H04o/5ciM7SP5t8Nf/ECI3EcCadz+/BtMILj5xSiutRS6bSDFcEO6mMU5htxdLcpNgJpUyidXRH/nddXqug5Ew5ZsTX4W+6Y+AmKl29uBNKFkfFI2j1mI+v4YUXMzfhhXqnmCBkpV2bOwWuQQW6AbS3wp6l9QzwF0qWnfO6pdlUWDHVQujD3LjZInNVgRS/Wo
  template:
    metadata:
      name: eventhub-alerts
      namespace: eventhub
