---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: eventhub
spec:
  encryptedData:
    .dockerconfigjson: AgBxjHLoSnFvriYnN88BGS9lxaTqIHoMjHwykZQTe7V8kiGCYy5mnfR5VXil27uRf8Cd66H+g3C5SVfHL4fW5q3CzKldvpGQlAu9A8TLWyeTvsdugFl+dGVvccjbVr4vxL7HhvBIlI2UMrEJU0OvJ8TCCclNsgue9uxVPmkQd35DM4jZk0kLFz/uMHcIfNTsncjl8JdfamTL5c30FFOuADXdpsrQv+fO2ZrJ9mvQmR6TFCz0Oak7DrI2ATg+AT8BCcym4MlN7zmbnp6cJmrq1mkbTo7hAMuM8nxN2UEvbktyWUMK0om0FiTQvpIoNOG0rhIDeZ0QcHrZVmVquv6e/pwdTfawnNCydFq+5XUmIBjIeVFuGckAkQMri7IPEDwnVcqVCRz3YNeCDbbSCCuDl9rbYaAXsITELoDf+FSh/QZDie8cpeEKPNoogUzUcZ9/Cr0NqU9ihK4S8Zeb14Exp4sT0MdOIvh73+LQV094hG9rYEcXMRGqpY+W2XAYsKVQNNlxRhLSFXfmLldoSuZ8GHfhFE+ZZs0Zzgd6trPZx+jTiQsz6OCAo6D/FSnNH+aSqvkKokCMiUcHp8R2RIBCEVCOCcqH3vMCI+W09INrl1hgJWsZP6A/HpDjkQnYz/O0ls5bzs4nm1mSBkBQjgbQIaukaIOgG9ZSfBP71MkKPAmWxGUhfYACVb26o4qOlJ7jHsaDMbi1G5t8ssHQluu7ZAaieqKCdKRBoNj3ufYY5DQYMJLpY/tknlBkzlG4FYRXaRewYmTwE78zWBOava6vUzEpzK9e1+6hkSFeWLSlfd9Y6dquIg0D2zvz0VQOO0NdlbNCQV46tla4ELccEC4tciQfHKALgN/nwm2UDA1y6SSx61fk5iHlUEWhhR0dOQHdshOeWYG0iZ+MtXrAMy69aedei7QxGCs3nxe8JxEFlEF1e9iWLyFQj09s
  template:
    metadata:
      name: ghcr-pull
      namespace: eventhub
    type: kubernetes.io/dockerconfigjson
