---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: eventhub
spec:
  encryptedData:
    .dockerconfigjson: AgBFLNgAulthSQittz6AiFovCbBGE99WdZCHszNGUmxPS7phwkHQJBUVtj60fLKSZhbjHMFjN86vGBSUDRDRiOkcBbgLOu1yHYSK1LvaBKg4EgNwLlM7QrYYRxjD163s17cCz/GwBCVrpDfJrwuHie9oAsjMbwYPWFuhDupCALLy7vuWw6mNQ7Omfm0ge0N7VC7vumEvL0PpRIjFv60BBef71QNdF+iIqY3FYdBnm4oAMN2MXZ4DP4Q13lrTVPIG0+icIEz+Xn1x46BUQDlZZ5gS+KHNRw7UJ5d2F72rE5/GEIJIcHSItzJRt/km4ikcAx69d9vgzyMo0vxKZbU54xA9q44A8pl56KyxftEApcoDcwV/9nKlnbM3/JcjrmSvEbILXlTOnamX0QP9VNrr3n/y3PwmQ/UNj4a093g14dtIOL1Wq6x62f2j0cjbQOR2RIJkHkAn1URLNcO5Q1KMbOo5U37imqhpGwnLz3czdejvvdF1A7pf6iKwg7D/fDOcSicoQ7xB+2EqB6c8v0EEiG3UTR56Qn1R+Oc4AZCs+qRffd/+fqiTUKwgQyqnO+XYyBysm9MBOEBJBmNd8XP9yHLbAZS+IVjNZGCmG6SNJmhSA4tQ/No3evqH+WBuJ9ANaQh0Q0OkB6RXi+RgWmEHCtnu+r8sbaNNLw9QS9EvHBHpCG0Ri8AefflhB5lKdUMDYWUfTv5w0sw3r/NTtdxk8hT46i6rX3zrj18Qls0W3oevFzSyFtRECh1i3poUx4U/V6LKIhDdJMXkZFljxHFGNy7vbCJFu31lbuj/Lw75hRHtlEG9vM78xRFzDZV+4Pne/M+mcjP/bGh5hmkZSJCCFs/7zqAbZJoeev00HYXwe59Ctohdrn5uSeIjVuYCfXTyA61p6zeeO78uEV2XZIPNS48ekOxHP8F2jS6UL7bLo+98ZNBDli58ufbg9vTPRxRdBEXlL4X/nrwjfbQR1bUFdeyIUgy3IxCIVewNb3iA4FxiXcVNir/yJOYqJSLCZ+ac6x4hcFNElGx5RWjgLNi7G1/6+4XMxErhQOVx9WDygOq5BkizF67KPu9Hdgiy5FTS7g+WxTUDRmXGR+3sFQWxXfuwDYcTnJt3eNhyRiIVjq3uo3atSK5v
  template:
    metadata:
      name: ghcr-pull
      namespace: eventhub
    type: kubernetes.io/dockerconfigjson
