---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: eventhub-alerts
  namespace: eventhub
spec:
  encryptedData:
    discord-webhook-url: AgBUG7kXbZlJyjlsTBFOyMFpqxnP0Qly6R8Vfxg6Rb+fzejWR4FgxzrZ+3ww6RKkKa8BRwYesaErOytgUHL0+9fqJgDxdjq/ZCiSD8HwB+aFPl/DzIH0glh6SdvFaVEX2kzZeza4sTRQNougoqYzbfxt2qBI8TOTGZwhojnEh7eHLl4sgf1aazZJlUdIY99w0blaI6+j4lA672Lbmpr6ehlPao715/lx/do+ya0qG7GoGs/HmKOCIH2jnYyhFuytwJVLJsmsBFFH0wQN0wuvIW0OzzvzWrBPZ/HtUmMES8eOxh2UYo8wcxJ5zCOKUDBCBWk58qr/ulFncgkrDkswX/F1IBUz7IvJ3utkKTrUsLYa7ooBS1SxrjpEd+DAjuzTkctuoWtki/RbKSIerfbX7FlyoCHDFk8953GEM7Ylz74Ceu30VUXKoLUTVN4uxbPB0UQZD34N8owY4OqWye0mXB6ZW0h8u4HYO7W+ISmkh735HS7Cc98084NFc9yDUZER6zFtIbLQvMrni8pxMaupCgvZkR1A2yEini0FwSBluSI86EStrmOAcAA9wLHLP4VaeIOrauKAr7T4vRrMJ00H2NC7a7daqDVlAeHr7pa+w1j0AdnQzIspCtoU/arkQ4QVVc7iVpkzh+Y+zFNJ/ZrqHpBK0Oihqlqjb0g8KXblj4EDIKjh7acqRuLURsKBzWLO9cRWdlVnH89BfoRU1FJjeKw2QIXazR32M7dYnWJjPB+ay5KloYgCihGwLxlrH0bmBtVpzEFXhrt5Z63FjseowQOTFwOi/CWCCNIU2xwAIaOuSbirGTWCWVw9VbweY6lUI/PFb61caexrxn4pn72bXwAEOLeBejzBjbfn
  template:
    metadata:
      name: eventhub-alerts
      namespace: eventhub
