---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: eventhub
spec:
  encryptedData:
    .dockerconfigjson: AgBJB/gLEhkhXvB9wU+Ph7nJ8pBLsHfDwiTr+32TyomHwaz1ijoHbm77gFQMJcuwFLCeN69GENvd/LFuO8Aemn7P7SMLurOzl04ZyEl9W8rnNJ+F9tk1lHZDxEy2G+H+10rEBAEk2wkU28A1plQ/KlFKRgHZaAlsq7AVY5cJ9iIduHiV876FdHHl+UCrLxevlMgJaw/V9GkuJ0Y7JAty3oEbgPO9p3P5NIpaVSM94gr/XXDFOn7Fy6P3tSqJ0gni2hn6oPeU7sdy41pw4gXJjDVcwcdQaHmkSlT4Y+FQEOI5vTrxxNtHJiSIvdE256NYOfnAg1wGtG5kEiRf5eMt/P58X+c3M6oWGj/LnthbPUsh6W+qkQUDeprUh/riaqxaZugA8E7X4uuDfDlvvB8nY6rwPbzBleNCssSHox5vkuiVfz+R1DCEpXlrT9WAZSb4rlORhNUQr2M0z3oyDe6kjwDldADWAe9Ys1P2VENeyb2OAjfZO1ixQn9X2NQoio/jKJfDqQbvsdME91QoP67962HucrUMQkOdbXcLVWmIWmtf7SY5zJx/t5cWjjOjiJF7PKsct7cHUIN5h3gSt6opCzqvfKAP0xnq0vp+t/aZfgm440iWQELwx/hSj0XRybybSqwiiFhrPhc7F0o+EX8gW/gvk4ZUHf10stnsKn67Cf0OC4fQ16uOGuPMkqcs6HPFPBqk065j0zGSN39T0QDZOHqXPrlkwjbsspjjNxAJbjY8b4655Qs0dxVCPQZB114f5f9CQk8rblvoVEAZ1dbcxkTMD4z4EHabZyJxKHFYAGVNyx+01qH8bDletsGXkxVYWbxYGwO5ArTLHFfmejTU4MOeI/n7Ugzklehqvj3ZjnSfQZIQbs+Sno0+wHsaxNBhoOotxtuvug6YFVOKM8K3MyYfOzf/wfcMSFv4wOpITW+jg448ZbeOk5hP
  template:
    metadata:
      name: ghcr-pull
      namespace: eventhub
    type: kubernetes.io/dockerconfigjson
