apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eventhub.fullname" . }}-postgres-init
  labels:
    {{- include "eventhub.labels" . | nindent 4 }}
data:
  10-init.sh: |
{{ .Files.Get "files/postgres-init.sh" | indent 4 }}
